name: media_player_trainee
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.8
  intl: ^0.18.1
  video_player: ^2.8.1
  audioplayers: ^5.2.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/gifts/
    - assets/imgs/
    - assets/musics/
    - assets/videos/
    - assets/response/
